- name: Создание конфига для клиента, для подключения к openvpn серверу
  hosts: openvpn_server
  become: true
  tasks:
    - name: Проверка что переменная с именем пользователя передана
      ansible.builtin.fail:
        msg: "Переменная 'client_name' не была передана через extra-vars"
      when: client_name is not defined

    - name: Создать каталог для конфигов клиентов
      ansible.builtin.file:
        path: /etc/openvpn/clients
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Копируем сертификат openvpn сервера
      ansible.builtin.copy:
        src: /etc/openvpn/ca.crt
        dest: /etc/openvpn/easy-rsa/pki/ca.crt
        remote_src: yes

    - name: Копируем ключ сертификата openvpn сервера
      ansible.builtin.copy:
        src: /etc/openvpn/ca.key
        dest: /etc/openvpn/easy-rsa/pki/private/ca.key
        remote_src: yes

    - name: Генерация сертификата клиента
      ansible.builtin.command: /etc/openvpn/easy-rsa/easyrsa gen-req {{ client_name }} nopass
      args:
        chdir: /etc/openvpn/easy-rsa

    - name: Подписываем сертификат клиента
      ansible.builtin.command: /etc/openvpn/easy-rsa/easyrsa sign-req client {{ client_name }}
      args:
        chdir: /etc/openvpn/easy-rsa

    - name: Чтение содержимого файла ca.crt
      ansible.builtin.slurp:
        path: /etc/openvpn/ca.crt
      register: ca_crt

    - name: Чтение содержимого файла {{ client_name }}.crt
      ansible.builtin.slurp:
        path: /etc/openvpn/easy-rsa/pki/issued/{{ client_name }}.crt
      register: client_crt

    - name: Чтение содержимого файла {{ client_name }}.key
      ansible.builtin.slurp:
        path: /etc/openvpn/easy-rsa/pki/private/{{ client_name }}.key
      register: client_key

    - name: Создаем ovpn конфиг
      ansible.builtin.copy:
        dest: /etc/openvpn/clients/{{ client_name }}.ovpn
        content: |
          client
          dev tun
          proto udp
          remote 5.35.112.132 1194
          resolv-retry infinite
          nobind
          persist-key
          persist-tun
          remote-cert-tls server
          verb 3
          
          <ca>
          {{ ca_crt['content'] | b64decode }}
          </ca>
          
          <cert>
          {{ client_crt['content'] | b64decode }}
          </cert>
          
          <key>
          {{ client_key['content'] | b64decode }}
          </key>

    - name: Чтение содержимого конфига клиента
      ansible.builtin.slurp:
        path: /etc/openvpn/clients/{{ client_name }}.ovpn
      register: client_config

    - name: |
        Конфиг клиента можно увидеть по пути /etc/openvpn/clients/{{ client_name }}.ovpn
        Также вот вывод здесь:
      ansible.builtin.debug:
        msg: |
          {{ client_config['content'] | b64decode }}
