- name: Install and configure K3s and Helm on server
  hosts: k3s_master
  become: true
  tasks:
    - name: Download and install K3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s
      environment:
        K3S_KUBECONFIG_MODE: "644"

    - name: Ensure the systemd service directory exists
      file:
        path: "/etc/systemd/system/k3s.service.d"
        state: directory
        mode: "0755"

    - name: Create systemd drop-in to configure K3s service parameters
      copy:
        dest: "/etc/systemd/system/k3s.service.d/override.conf"
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/local/bin/k3s server --https-listen-port 6443 --bind-address 10.8.0.1 --advertise-address 10.8.0.1 --node-ip 10.8.0.1
      notify:
        - Reload systemd and restart k3s service

    - name: Verify K3s installation
      command: /usr/local/bin/k3s --version
      register: k3s_version
      changed_when: false

    - name: Show K3s version
      debug:
        msg: "K3s installed successfully. Version: {{ k3s_version.stdout }}"

    - name: Download and install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Verify Helm installation
      command: helm version --short
      register: helm_version
      changed_when: false

    - name: Show Helm version
      debug:
        msg: "Helm installed successfully. Version: {{ helm_version.stdout }}"

  handlers:
    - name: Reload systemd and restart k3s service
      systemd:
        name: k3s
        daemon_reload: yes
        state: restarted
