- name: Установка OpenVPN и локального DNS
  hosts: openvpn_server
  become: yes
  tasks:
    - name: Установить необходимые пакеты
      apt:
        name:
          - openvpn
          - easy-rsa
          - dnsmasq
        state: present
        update_cache: yes

    - name: Создать каталог для ключей
      file:
        path: /etc/openvpn/easy-rsa
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Копировать файлы Easy-RSA
      copy:
        src: /usr/share/easy-rsa/
        dest: /etc/openvpn/easy-rsa
        remote_src: yes

    - name: Создать vars файл
      copy:
        dest: /etc/openvpn/easy-rsa/vars
        content: |
          set_var EASYRSA_ALGO "ec"
          set_var EASYRSA_DIGEST "sha512"
          set_var EASYRSA_KEY_SIZE 4096
          set_var EASYRSA_REQ_COUNTRY "RU"
          set_var EASYRSA_REQ_PROVINCE "Moscow"
          set_var EASYRSA_REQ_CITY "Moscow"
          set_var EASYRSA_REQ_ORG "MyVPN"
          set_var EASYRSA_REQ_EMAIL "ikpolux@mail.ru"
          set_var EASYRSA_REQ_OU "IT"
          set_var EASYRSA_BATCH "1"

    - name: Инициализация PKI
      command: /etc/openvpn/easy-rsa/easyrsa init-pki
      args:
        chdir: /etc/openvpn/easy-rsa

    - name: Создание CA
      command: /etc/openvpn/easy-rsa/easyrsa build-ca nopass
      args:
        chdir: /etc/openvpn/easy-rsa

    - name: Генерация серверного ключа и сертификата
      command: /etc/openvpn/easy-rsa/easyrsa build-server-full server nopass
      args:
        chdir: /etc/openvpn/easy-rsa

    - name: Копирование файлов в директорию OpenVPN
      shell: |
        cp /etc/openvpn/easy-rsa/pki/ca.crt /etc/openvpn/
        cp /etc/openvpn/easy-rsa/pki/private/server.key /etc/openvpn/
        cp /etc/openvpn/easy-rsa/pki/issued/server.crt /etc/openvpn/

    - name: Настроить dnsmasq
      copy:
        dest: /etc/dnsmasq.conf
        content: |
          listen-address=10.8.0.1
          interface=tun0
          domain=myvpn.local
          expand-hosts
          local=/myvpn.local/
          address=/server.myvpn.local/10.8.0.1
          address=/upikoth.myvpn.local/10.8.0.2
          server=8.8.8.8
          server=8.8.4.4

    - name: Копировать конфигурацию сервера OpenVPN
      copy:
        dest: /etc/openvpn/server.conf
        content: |
          port 1194
          proto udp
          dev tun
          ca /etc/openvpn/ca.crt
          cert /etc/openvpn/server.crt
          key /etc/openvpn/server.key
          dh /etc/openvpn/dh2048.pem
          topology subnet
          server 10.8.0.0 255.255.255.0
          ifconfig-pool-persist /var/log/openvpn/ipp.txt
          keepalive 10 120
          persist-key
          persist-tun
          status /var/log/openvpn-status.log
          verb 5
          push "dhcp-option DNS 10.8.0.1"
          push "dhcp-option DOMAIN myvpn.local"
          log /var/log/openvpn.log
          data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305
          auth SHA256

    - name: Создание DH файла
      command:
        cmd: "openssl dhparam -out /etc/openvpn/dh2048.pem 2048"
        creates: /etc/openvpn/dh2048.pem

    - name: Разрешить переадресацию пакетов
      lineinfile:
        path: /etc/sysctl.conf
        line: "net.ipv4.ip_forward = 1"
        state: present

    - name: Применить изменения sysctl
      command: sysctl -p

    - name: Настроить iptables
      iptables:
        table: nat
        chain: POSTROUTING
        jump: MASQUERADE
        out_interface: eth0
        source: 10.8.0.0/24
      notify:
        - Save iptables

    - name: Выключить systemd-resolved, чтобы освободить 53 порт для dnsmasq
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no

    - name: Указать dnsmasq в качестве dns на сервере
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 10.8.0.1
          options edns0 trust-ad
          search .

    - name: Запустить OpenVPN
      systemd:
        name: openvpn@server
        state: started
        enabled: yes

    - name: Перезапустить dnsmasq
      systemd:
        name: dnsmasq
        state: restarted
        enabled: yes

  handlers:
    - name: Save iptables
      command: iptables-save > /etc/iptables/rules.v4
